name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.0', '8.1', '8.2', '8.3', '8.4' ]
        prefer-lowest: [ '', '--prefer-lowest --prefer-stable' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate composer.json
      run: composer validate

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check style
      run: composer run-script check-style

    - name: Run test suite
      run: composer run-script test
